name = "Realliance Community"
author = "Realmic"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2635196e8a464f398486bae5184e0970d8cc2b242f869d79213bb748307fb3b"

[versions]
fabric = "0.15.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
