name = "Realliance Community"
author = "Realmic"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8af1a93828ae6f27419f12c154415d978235f7db76de55124453ee1c70e423a8"

[versions]
fabric = "0.15.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
