name = "Realliance Community"
author = "Realmic"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45d3f9f7896289e7d0dc403d92631eeda5eaecfeccfff22f5154b216e56ca90d"

[versions]
minecraft = "1.20"
quilt = "0.22.0"

[options]
acceptable-game-versions = ["1.20", "1.20.1", "1.20.2", "1.20.3", "1.20.4"]
