name = "Realliance Community"
author = "Realmic"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "730c94ef3a7ffdde2cb8c67fe1094d322fe3835163f42b1edfaa59cd949ff88a"

[versions]
fabric = "0.15.5"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
