name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rrbutani/use-nix-shell-action@v1
        with:
          file: shell.nix
      - name: Set Version to 0.0.0 for Artifact
        run: deno run -A mod.ts reset
      - name: Export Modpack
        run: packwiz mr export
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: modrinth-export
          path: Realliance Community-0.0.0.mrpack
